# Generated by Django 3.0.8 on 2020-07-30 08:43

from django.db import migrations, models
import django.db.models.deletion
import photo.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='설명')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=32, verbose_name='제품명')),
                ('pcost', models.CharField(max_length=64, verbose_name='가격')),
                ('pcontent', models.TextField(blank=True, verbose_name='상세설명')),
                ('pimage', photo.fields.ThumbnailImageField(upload_to='photo/%Y/%m', verbose_name='이미지')),
                ('psize', models.CharField(blank=True, max_length=64, verbose_name='크기')),
                ('pweight', models.CharField(blank=True, max_length=64, verbose_name='무게')),
                ('pship', models.CharField(max_length=64, verbose_name='배송방법')),
                ('pstore', models.CharField(max_length=64, verbose_name='보관장소')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('put', models.IntegerField(default=0, verbose_name='입고수량')),
                ('putdate', models.CharField(blank=True, max_length=128, verbose_name='입고날짜')),
                ('stock', models.IntegerField(default=0, verbose_name='재고수량')),
                ('release', models.IntegerField(default=0, verbose_name='출고수량')),
                ('redate', models.CharField(blank=True, max_length=128, verbose_name='출고날짜')),
                ('rfid', models.CharField(blank=True, max_length=256, verbose_name='RFID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Category')),
            ],
            options={
                'ordering': ('pname',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=32, verbose_name='주문자 이름')),
                ('ocall', models.CharField(max_length=64, verbose_name='연락처')),
                ('oaddress', models.CharField(max_length=256, verbose_name='주소')),
                ('oemail', models.CharField(blank=True, max_length=128, verbose_name='이메일')),
                ('omemo', models.TextField(blank=True, verbose_name='배송메모')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Product')),
            ],
            options={
                'ordering': ('oname',),
            },
        ),
    ]
