# Generated by Django 3.0.8 on 2020-08-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200803_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_product',
            options={'ordering': ('order',)},
        ),
    ]
