# Generated by Django 3.0.8 on 2020-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_delete_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
