# Generated by Django 3.0.8 on 2020-08-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_alarm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_product',
            options={},
        ),
        migrations.AddField(
            model_name='order_product',
            name='state',
            field=models.CharField(blank=True, default='register', max_length=64, verbose_name='처리상태'),
        ),
    ]
