# Generated by Django 3.0.8 on 2020-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20200814_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, default='register', max_length=64, verbose_name='처리상태'),
        ),
    ]
