# Generated by Django 3.0.8 on 2020-08-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_auto_20200815_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('state',)},
        ),
    ]
