# Generated by Django 3.0.8 on 2020-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_auto_20200819_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='no',
            field=models.CharField(max_length=16, null=True, verbose_name='출고번호'),
        ),
    ]
