# Generated by Django 3.0.8 on 2020-08-31 12:46

from django.db import migrations, models
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_order_product_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarm',
        ),
        migrations.AlterField(
            model_name='face',
            name='fimage',
            field=photo.fields.ThumbnailImageField(upload_to='face/%Y/%m', verbose_name='face 이미지'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, default='input', max_length=64, verbose_name='처리상태'),
        ),
    ]
