# Generated by Django 3.0.8 on 2020-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20200831_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='put',
            field=models.IntegerField(default=1, verbose_name='입고수량'),
        ),
    ]
