# Generated by Django 3.0.8 on 2020-09-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_auto_20200901_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='putdate',
        ),
    ]
