# Generated by Django 3.0.8 on 2020-09-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_remove_product_putdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='redate',
        ),
    ]
