# Generated by Django 3.0.8 on 2020-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_remove_product_redate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='재고수량'),
        ),
    ]
