# Generated by Django 3.0.8 on 2020-09-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_auto_20200902_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='put',
            field=models.IntegerField(default=0, verbose_name='입고수량'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='재고수량'),
        ),
    ]
