# Generated by Django 3.0.8 on 2020-09-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0017_auto_20200902_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='putdate',
            field=models.CharField(blank=True, max_length=128, verbose_name='입고날짜'),
        ),
    ]
