# Generated by Django 3.0.8 on 2020-09-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0018_product_putdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('oname',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
