# Generated by Django 3.0.3 on 2020-10-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0020_auto_20200916_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=-1, verbose_name='재고수량'),
        ),
    ]
