# Generated by Django 3.0.3 on 2020-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0021_auto_20201005_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='재고수량'),
        ),
    ]
