# Generated by Django 3.0.3 on 2020-10-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0023_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='no',
            field=models.IntegerField(max_length=16, null=True, verbose_name='출고번호'),
        ),
    ]
