# Generated by Django 3.0.3 on 2020-10-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0024_auto_20201005_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='no',
            field=models.IntegerField(null=True, verbose_name='출고번호'),
        ),
    ]
