# Generated by Django 3.0.3 on 2020-11-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0026_auto_20201007_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='no',
        ),
    ]
