# Generated by Django 3.0.3 on 2020-11-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0027_remove_order_product_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='no',
            field=models.IntegerField(blank=True, null=True, verbose_name='출고번호'),
        ),
    ]
