# Generated by Django 3.0.8 on 2020-07-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twsuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twsuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='twsuser',
            name='registered_dttm',
        ),
        migrations.AddField(
            model_name='twsuser',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='업체주소'),
        ),
        migrations.AddField(
            model_name='twsuser',
            name='call',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='업체번호'),
        ),
        migrations.AddField(
            model_name='twsuser',
            name='company',
            field=models.CharField(max_length=128, null=True, verbose_name='업체명'),
        ),
        migrations.AddField(
            model_name='twsuser',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='사용자 이메일'),
        ),
        migrations.AddField(
            model_name='twsuser',
            name='pw',
            field=models.CharField(max_length=64, null=True, verbose_name='사용자 비밀번호'),
        ),
        migrations.AddField(
            model_name='twsuser',
            name='pwc',
            field=models.CharField(max_length=64, null=True, verbose_name='비밀번호 확인'),
        ),
        migrations.AlterField(
            model_name='twsuser',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='사용자 아이디'),
        ),
        migrations.AlterField(
            model_name='twsuser',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='사용자 이름'),
        ),
    ]
