# Generated by Django 3.0.8 on 2020-07-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twsuser', '0002_auto_20200724_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twsuser',
            name='pwc',
        ),
    ]
